Dracula5
freeboardgames/FreeBoardGames.org pull request #658
Opened 2020-11-06 22:06 UTC by Spooky-0

#### Checklist

* [ ] Use a separate branch in your local repo (not `master`).
* [ ] I've read and agree with the [contribution guidelines](https://www.freeboardgames.org/docs/?path=/story/documentation-contributing--page).

2020-11-06 22:44 UTC, flamecoals commented
This is overall looking good! I will just do some play testing and if I don't find anything major I am going to approve :)

2020-11-07 06:48 UTC, flamecoals commented
I played the game, and I like the simplicity of the UI with emojis :D.

The game is also working well on mobile, and given that you have good test coverage for the rules, we can publish it :).

Only a few things that could be improved and iterated in the future:
- The tap target for the emojis are small on mobile. Users might click by mistake on the wrong action.
- For players that are waiting for another player, it would be nice to show "Waiting for X..." instead of the action title.
- For the voting action, it would be nice to reiterate who is the mayor and priest on the message.
- It would be nice to have at least one UI test
- The table works now as emojis, but I believe a simple SVG would be even better.

2020-11-07 06:59 UTC, flamecoals commented
Ok, just found a blocker: I don't see you rendering the game over page, and your tests dont include this condition either.
We can either merge the PR now but keep it in development, or fix this and publish it :).

2020-11-07 07:00 UTC, flamecoals requested changes

2020-11-07 07:03 UTC, flamecoals commented
I also noticed that the `endIf` that should finish the game is mis-spelled (lower case I: `endif`)

2020-11-07 07:14 UTC, flamecoals commented on web/src/games/secretDracula/board.tsx
>          <GameLayout gameArgs={this.props.gameArgs} allowWiderScreen={true}>
Here is an example of rendering the game over page:
https://github.com/freeboardgames/FreeBoardGames.org/blob/8b6306b5f4fa82a9b61589cb077612c180e610bd/web/src/games/tictactoe/board.tsx#L83

Here is an example on how to check if the game is over on the test:
https://github.com/freeboardgames/FreeBoardGames.org/blob/8b6306b5f4fa82a9b61589cb077612c180e610bd/web/src/games/tictactoe/game.test.ts#L53

2020-11-15 15:00 UTC, Spooky-0 commented on web/src/games/secretDracula/game.test.ts
> +  // TODO: Now the game should be over, as Dracula is dead!
done.

2020-11-15 15:00 UTC, Spooky-0 commented on web/src/games/secretDracula/board.tsx
>          <GameLayout gameArgs={this.props.gameArgs} allowWiderScreen={true}>
done. Its not pretty, but done.

2020-11-15 15:00 UTC, closed without merging